#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Theres tite, float, fullscreen states
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Colors, uses the OFFICIAL cyberpunk yellow :3
# Source:
# https://reddit.com/r/MechanicalKeyboards/comments/k6kduq/
bspc config normal_border_color "#F3E600"
bspc config focused_border_color "#F3E600"
bspc config active_border_color "#F3E600"


polybar &
xsetroot -cursor_name left_ptr &
setxkbmap us &
picom &
nitrogen --restore
